name: E2E Test Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '.github/workflows/**'
      - 'quickstart/**'

jobs:
  e2e-check:
    runs-on: [self-hosted, 1ES.Pool=azterraform]
    environment:
      name: acctests
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          dir_names: "true"
          separator: ","
          files: "quickstart/*"
          files_ignore: "**/TestRecord.md"
      - name: test pr
        run: |
          az login --identity --username $MSI_ID > /dev/null
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          export CHANGED_FOLDERS="${{ steps.changed-files.outputs.all_changed_files }}"
