name: Pre Pull Request Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '.github/workflows/**'
      - 'quickstart/**'

jobs:
  prepr-check:
    runs-on: [self-hosted, 1ES.Pool=azure-terraform-doc]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "!quickstart/**"
          foldersOnly: true
          format: csv
      - name: test pr
        run: |
          az login --identity --username $MSI_ID > /dev/null
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          docker run --rm -v ${pwd}:/src -w /src/test --network=host -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_USE_MSI=true -e CHANGED_FOLDERS="${{ steps.get_changed.outputs.changed }}" mcr.microsoft.com/azterraform go test -v ./e2e