name: Pre Pull Request Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '.github/workflows/**'
      - 'quickstart/**'

jobs:
  prepr-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "!quickstart/**"
          foldersOnly: true
          format: csv