name: Main Branch Push
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'quickstart/**'
jobs:
  main-branch-push:
    runs-on: ubuntu-latest
    steps:
      - name: get-default-branch
        run: |
          branch=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY" | jq -r '.default_branch')
          echo "default_branch=$branch" >> $GITHUB_ENV
      - uses: 8BitJonny/gh-get-current-pr@2.1.0
        id: PR
      - uses: actions/download-artifact@v3
        with:
          name: TestRecord-${{ steps.PR.outputs.number }}
          path: TestRecord
      - name: Update
        run: |
          sh scripts/update-test-record.sh
          git add **/TestRecord.md
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Update TestRecord'
          branch: ${{ env.default_branch }}